# Please read the README for an explanation of how to use this
# meta-configuration file first.

######################################################################
# Html list configs
html_list:
  template: index.html.erb
  outfile: index.html

######################################################################
# Default configs
#
# Specify default values for attributes. If a given host does not
# declare one of these keys below, the default gets used.
defaults:
  # The erb template file to generate site-specific files from.
  # It should be an absolute path or a path relative to the
  # Rakefile/config.yml file. Edit the settings within it for all
  # generated files, or add more erb markup and configuration here to
  # customize it further.
  template: awstats.model.conf.erb
  # Format string that specifies the generated filenames. It should
  # have a single %s in it that specifies where to put a service-domain
  # pair. For example, suppose a domain is somedomain and the service is
  # http, and the targetformat is "awstats.%s.conf". Then the generated
  # configuration filename will be "awstats.http-somedomain.conf.
  targetformat: awstats.%s.conf
  domain: localhost
  service: http
  aliases:
  logfile: /var/log/apache2/access_log
  # See http://awstats.sourceforge.net/docs/awstats_config.html#LogFormat
  # for Logformat strings.
  #
  # My apache vhost log format string:
  #"%t %h %l %u %v \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" VLOG=%{VLOG}e"
  logformat: "%time1 %host %other %logname %virtualname %methodurl %code %bytesd %refererquot %uaquot %other"

######################################################################
# Site configs
configs:
- domain: www.aedifice.org
  service: http
  aliases:
    - localhost
    - ouroboros.aedifice.org
    - aedifice.org
    - ouroboros.local
    - ouroboros.homedns.org
  logfile: /var/log/apache2/access_log

- domain: dev.aedifice.org
  service: http
  aliases:
    - dev.ouroboros.local
    - dev.ouroboros.homedns.org
  logfile: /var/log/apache2/access_log

- domain: dev.aedifice.org
  service: https
  aliases:
    - dev.ouroboros.local
    - dev.ouroboros.homedns.org
  logfile: /var/log/apache2/ssl_access_log

- domain: blog.aedifice.org
  service: http
  aliases:
    - blog.ouroboros.local
    - blog.ouroboros.homedns.org
  logfile: /var/log/apache2/access_log

- domain: blog.aedifice.org
  service: https
  aliases:
    - localhost
    - blog.ouroboros.local
    - blog.ouroboros.homedns.org
  logfile: /var/log/apache2/ssl_access_log

- domain: lists.aedifice.org
  service: http
  aliases:
    - lists.ouroboros.local
    - lists.ouroboros.homedns.org
  logfile: /var/log/apache2/access_log

- domain: nethack.aedifice.org
  service: http
  aliases:
    - nethack.ouroboros.local
    - nethack.ouroboros.homedns.org
  logfile: /var/log/apache2/access_log

- domain: private.aedifice.org
  service: http
  aliases:
    - localhost
    - private.ouroboros.local
    - private.ouroboros.homedns.org
  logfile: "/var/log/apache2/access_log"


